version: '3'
services:
  nginx:
    image: nginx:1.12.2-alpine
    ports:
      - "443:443"
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/pki/nginx/certs
      - ./src/static:/var/www/static
  django:
    build: ./django
    env_file: ./django/.django_env
    environment:
      DATABASE_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/django
    command: gunicorn app.wsgi -b 0.0.0.0:8080
  postgres:
    build: ./postgres
    env_file: ./postgres/.postgres_env
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: 'postgres -c config_file="/etc/postgresql.conf"'
volumes:
  pgdata:
