version: '3'
services:
  nginx:
    build: 
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    environment:
      BACKEND: django
    depends_on:
      - django
    volumes:
      - ./nginx/certs:/etc/pki/nginx/certs
  django:
    build: 
      context: ./
      dockerfile: ./django/Dockerfile
    env_file: ./django/.django_env
    environment:
      DATABASE_HOST: postgres
      NOSQL_DATABASE_HOST: xxxx
    depends_on:
      - postgres
      - mongo
  postgres:
    build: 
      context: ./
      dockerfile: ./postgres/Dockerfile
    env_file: ./postgres/.postgres_env
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: 'postgres -c config_file="/etc/postgresql.conf"'
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
volumes:
  pgdata:
  mongodata:
