apiVersion: v1
kind: ReplicationController
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: django
          image: tetsis/simple-django-app
          ports:
            - name: django
              containerPort: 8080
          env:
            - name: DATABASE_PASSWORD
              value: django
            - name: DATABASE_USER
              value: django
            - name: DATABASE_NAME
              value: django
            - name: DATABASE_HOST
              value: xxxx
            - name: NOSQL_DATABASE_NAME
              value: django
            - name: NOSQL_DATABASE_USER
              value: django
            - name: NOSQL_DATABASE_PASSWORD
              value: django
            - name: NOSQL_DATABASE_HOST
              value: xxxx
        - name: proxy
          image: tetsis/simple-django-reverse-proxy
          ports:
            - name: http-server
              containerPort: 80
