apiVersion: v1
kind: ReplicationController
metadata:
  name: app1
  labels:
    app1: app1
spec:
  replicas: 1
  selector:
    app1: app1
  template:
    metadata:
      labels:
        app1: app1
    spec:
      containers:
        - name: django
          image: tetsis/simple-django-app
          ports:
            - name: django
              containerPort: 8080
          env:
            - name: DATABASE_PASSWORD
              value: django1
            - name: DATABASE_USER
              value: django1
            - name: DATABASE_NAME
              value: django1
            - name: DATABASE_HOST
              value: xxxx
        - name: proxy
          image: tetsis/simple-django-reverse-proxy
          ports:
            - name: http-server1
              containerPort: 80
