apiVersion: batch/v1
kind: Job
metadata:
  name: init_app
spec:
  template:
    spec:
      containers:
        - name: init_app
          image: tetsis/simple-django-app
          env:
            - name: DATABASE_PASSWORD
              value: django
            - name: DATABASE_USER
              value: django
            - name: DATABASE_NAME
              value: django
            - name: DATABASE_HOST
              value: xxxx
          command: ["sh",  "init.sh"]
      restartPolicy: Never