#!/bin/sh

psql -h $DATABASE_HOST -U $DATABASE_USER -c "CREATE ROLE $NEW_DATABASE_USER WITH LOGIN PASSWORD '$NEW_DATABASE_PASSWORD';"
psql -h $DATABASE_HOST -U $DATABASE_USER -c "GRANT $NEW_DATABASE_USER TO postgres;"
psql -h $DATABASE_HOST -U $DATABASE_USER -c "CREATE DATABASE $NEW_DATABASE_NAME OWNER $NEW_DATABASE_USER ENCODING 'utf8';"